### ISSUE TITLE
Black Delay screen when navigating to a specific page

### ISSUE THREAD

**Issue by zionnite** [hiennguyen92/flutter_callkit_incoming#93] opened 2022-04-19 10:29 UTC
Thank you sir, am very grateful for this package.

1) Whenever I accept an incoming call when navigating to a new page it first relaunch the app by showing black Delay screen before navigating to that specific screen

https://user-images.githubusercontent.com/10984801/163981542-8635d8d2-1e67-4737-a8ed-5a2ce5e77d25.mp4

2) When device is on lock screen and I accept an incoming call, it does not take me to the specific page, it just relaunch the app

https://user-images.githubusercontent.com/10984801/163983315-373581a8-5cd8-4777-aaa5-1ff7bc801351.mp4

3) When app is on Background and I received an incoming call, it just relaunch the app, it does not take me to the specific page as well

4) When app is not amongst the recent open apps, when I accept an incoming call, it relaunch the app again

Am using the package latest version +7

**Comment by Condelab** [comment] 2022-04-20 21:36
hello @zionnite want to know how i solved this?

I did a shared pref. save in `case CallEvent.ACTION_CALL_ACCEPT:` (you can never navigate here, not in a 100 years)

Once i pick the call the app saves my shared pref (with all the call event data) and does a reload (as u said) right? 

The next thing is that your first screen will show after the reload (lets say your splash screen).

In my splash screen (first screen), inside the `initState()` method, i check the shared pref. for the call data if returns null it means no call, i can proceed with life normally. 

if its not null then the screen is launched as a result of a call, hence i can navigate the user to the audio or video call screen as i have saved the call data in my shared pref.

This is more of a flow thing NOT some complex programming as you would have thought.

(`onDispose` and `onEndCall` of your call page, always clear the call shared pref. to avoid it intercepting your first screen)

**Comment by hiennguyen92** [comment] 2022-04-21 06:15
i will check the issue relaunch. maybe it's me

**Comment by zionnite** [comment] 2022-04-21 07:12
> hello @zionnite and @hiennguyen92 want to know how i solved this?
> 
> I did a shared pref. save in `case CallEvent.ACTION_CALL_ACCEPT:` (you can never navigate here, not in a 100 years)
> 
> Once i pick the call the app saves my shared pref (with all the call event data) and does a reload (as u said) right?
> 
> The next thing is that your first screen will show after the reload (lets say your splash screen).
> 
> In my splash screen (first screen), inside the `initState()` method, i check the shared pref. for the call data if returns null it means no call, i can proceed with life normally.
> 
> if its not null then the screen is launched as a result of a call, hence i can navigate the user to the audio or video call screen as i have saved the call data in my shared pref.
> 
> This is more of a flow thing NOT some complex programming as you would have thought.
> 
> (`onDispose` and `onEndCall` of your call page, always clear the call shared pref. to avoid it always intercepting your first screen)

have done something similar before posting this question, am not using shared pref. am using firebase snapshot with stream builder to detect the behavior of where to navigate to but yet issue persists.

thanks for your warm response.

**Comment by WilliandyMTMH** [comment] 2022-04-22 13:38
I had similar issue too.

**Comment by zionnite** [comment] 2022-04-22 19:32
@hiennguyen92 
it's of joyful heart I write this statement Mr @hiennguyen92 , everything I needed your package for has been accomplished but the issue I have right now is those highlighted above.

and I Yet highlight them again 

1) Whenever I accept an incoming call when navigating to a new page it first relaunches the app by showing a black Delay screen before navigating to that specific screen

2) When the device is on the lock screen and I accept an incoming call, it does not take me to the specific page, it just relaunches the app

3) When app is in the Background and I received an incoming call, it just relaunches the app, it does not take me to the specific page as well

4) When the app is not among the recent open apps when I accept an incoming call, it relaunches the app again

**I Am using the package's latest version +7**

**Comment by WilliandyMTMH** [comment] 2022-04-23 02:26
Temporarily  downgrade to version : **flutter_callkit_incoming: 1.0.1+6** solved my problem hope this can help you

**Comment by zionnite** [comment] 2022-04-23 06:17
> Temporarily  downgrade to version : **flutter_callkit_incoming: 1.0.1+6** solved my problem hope this can help you

Thanks for quick reply.

I thought version **1.0.1+6** has some bugs like duplication of incoming calls?


Please, what's the downside you are experiencing with **1.0.1+6**??

**Comment by zionnite** [comment] 2022-04-23 07:09
> Temporarily downgrade to version : **flutter_callkit_incoming: 1.0.1+6** solved my problem hope this can help you

just tried **1.0.1+6??**, it did not work



@hiennguyen92 have u taken a look into this?

**Comment by WilliandyMTMH** [comment] 2022-04-25 07:22
> > Temporarily downgrade to version : **flutter_callkit_incoming: 1.0.1+6** solved my problem hope this can help you
> 
> just tried **1.0.1+6??**, it did not work
> 
> @hiennguyen92 have u taken a look into this?

Make sure you are on **1.0.1+6** 
I check it from here : flutter pub outdated
if your version is still on 1.0.1+7 you have to delete ^ from your version number.

**Comment by zionnite** [comment] 2022-04-25 09:27
just did that unfortunately it did not work for me

**Comment by hiennguyen92** [comment] 2022-04-25 10:59
Sorry. I will check it

**Comment by amsyary** [comment] 2022-04-26 08:18
> flutter pub outdated

I've downgraded it, and the app still restarts

**Comment by zionnite** [comment] 2022-04-27 00:39
> > flutter pub outdated
> 
> I've downgraded it, and the app still restarts

Me too

**Comment by suhail600** [comment] 2022-04-27 04:44
> hello @zionnite and @hiennguyen92 want to know how i solved this?
> 
> I did a shared pref. save in `case CallEvent.ACTION_CALL_ACCEPT:` (you can never navigate here, not in a 100 years)
> 
> Once i pick the call the app saves my shared pref (with all the call event data) and does a reload (as u said) right?
> 
> The next thing is that your first screen will show after the reload (lets say your splash screen).
> 
> In my splash screen (first screen), inside the `initState()` method, i check the shared pref. for the call data if returns null it means no call, i can proceed with life normally.
> 
> if its not null then the screen is launched as a result of a call, hence i can navigate the user to the audio or video call screen as i have saved the call data in my shared pref.
> 
> This is more of a flow thing NOT some complex programming as you would have thought.
> 
> (`onDispose` and `onEndCall` of your call page, always clear the call shared pref. to avoid it always intercepting your first screen)

the problem is  not with splash screen , before splash screen there's a black screen for flutter before launching app , i have no splash screen in my app even though routing causes relaunching app , and routing is done in widgets binding post frame call back and  not in  CallEvent.ACTION_CALL_ACCEPT:`

**Comment by suhail600** [comment] 2022-04-27 04:46
still facing issue with routing , any fix available? please help

**Comment by zionnite** [comment] 2022-04-27 13:22
@hiennguyen92 😭😭😭😭

**Comment by hiennguyen92** [comment] 2022-04-28 09:31
can you use version master branch for check?

**Comment by zionnite** [comment] 2022-04-28 13:21
> can you use version master branch for check?

please, how do I do that

**Comment by hiennguyen92** [comment] 2022-04-28 15:12
flutter_callkit_incoming:
    git:
      url: git@github.com:hiennguyen92/flutter_callkit_incoming.git
      ref: master

**Comment by hiennguyen92** [comment] 2022-04-28 19:27
I just published v1.0.1+8, please check again.

**Comment by amsyary** [comment] 2022-04-28 21:13
new version v1.0.1+8, it's working no restart anymore, thank @hiennguyen92 
but now ringtone, do we have to setup a parameter to activate the ringtone?

**Comment by Condelab** [comment] 2022-04-28 21:49
@hiennguyen92 thanks alot for the support, this is appriciated.

The latest version` flutter_callkit_incoming: ^1.0.1+8 ` is not working on Android OS but works on IOS, I think its a gradle compatibility issue as stated below:

issue [https://github.com/hiennguyen92/flutter_callkit_incoming/issues/102](https://github.com/hiennguyen92/flutter_callkit_incoming/issues/102)

Thanks Again!

**Comment by amsyary** [comment] 2022-04-28 21:59
@Condelab i facing the same issue, but i just delete package cache from previous version and do `flutter clean`, and it's working fine in android

**Comment by suhail600** [comment] 2022-04-29 05:55
> I just published v1.0.1+8, please check again.

@hiennguyen92 this is the only package was stable till previous version with small problems, and thank you for this package , since the latest update , 
1. app is crashing on receiving the call accept (checked in vivo, oneplus, redmi, samsung phones)
2. call is not accepted when clicked and tapping two three times somewhat opens the app
3. black screen is gone in debug mode , but app needs restart to route to the specific page , and all was fine working in previous version in profile mode (no crashing , routing properly ,).
5. receiving 2 call popup for a single call.
6. all routing doesn't working in debug and profile mode

**Comment by hiennguyen92** [comment] 2022-04-29 08:27
https://github.com/hiennguyen92/flutter_callkit_incoming/blob/542c69ba4b956141423352f2fc885ff2eae08c58/example/lib/main.dart#L70

please `with WidgetsBindingObserver`

**Comment by suhail600** [comment] 2022-04-29 09:14
@hiennguyen92  tried every thing , app crashes , I already mensioned details in top comment please check .

**Comment by zionnite** [comment] 2022-04-29 12:07
> I just published v1.0.1+8, please check again.

It's working perfectly.
Bravo for this fixed.

**Comment by zionnite** [comment] 2022-04-29 12:08
But sir, when app is killed or terminated, push notifications does not display.

How can this be resolved?

**Comment by zionnite** [comment] 2022-04-29 12:16
> @hiennguyen92 thanks alot for the support, this is appriciated.
> 
> The latest version` flutter_callkit_incoming: ^1.0.1+8 ` is not working on Android OS but works on IOS, I think its a gradle compatibility issue as stated below:
> 
> issue [https://github.com/hiennguyen92/flutter_callkit_incoming/issues/102](https://github.com/hiennguyen92/flutter_callkit_incoming/issues/102)
> 
> Thanks Again!
> 

@Condelab check again, it's working perfectly for me

**Comment by zionnite** [comment] 2022-04-29 12:19
> But sir, when app is killed or terminated, incoming call does not display.
> 
> How can this be resolved?

@hiennguyen92

**Comment by hiennguyen92** [comment] 2022-04-29 14:48
@zionnite Please make sure to receive notifications. it working fine for me both android/iOS

**Comment by zionnite** [comment] 2022-04-29 14:49
> @zionnite Please make sure to receive notifications. it working fine for me both android/iOS

Let me double check again

**Comment by hiennguyen92** [comment] 2022-04-29 18:25
you can try new version 1.0.2(check example)).

**Comment by zionnite** [comment] 2022-04-30 00:37
Foreground it's working perfectly
Background it's working perfectly
No more relaunch

But when app is terminated or killed incoming call do not show.?

It's this beyond the scope of this package?

**Comment by hiennguyen92** [comment] 2022-04-30 02:58
you can try restarting the device.  There is some reason some VoIP or FCM push won't be received

**Comment by zionnite** [comment] 2022-04-30 11:06
> you can try restarting the device. There is some reason some VoIP or FCM push won't be received

@hiennguyen92 , I have checked, doubled checked, and triple checked

once app is killed or remove from recent app, it does not get any incoming notification

**Comment by amsyary** [comment] 2022-04-30 11:11
> 


I think this is beyond the scope of this issue, and the issue in this thread has been fixed, you should create a new issue

**Closed** 2022-04-30 11:15 UTC
