### ISSUE TITLE
PlatformException(error, call.arguments() must not be null, , null) , after calling await FlutterCallkitIncoming.endAllCalls();

### ISSUE THREAD

**Issue by sadaqatkarimi** [hiennguyen92/flutter_callkit_incoming#18] opened 2022-01-12 16:48 UTC
PlatformException(error, call.arguments() must not be null, , null) , 

after calling await FlutterCallkitIncoming.endAllCalls();

**Comment by marcoberetta96** [comment] 2022-01-12 20:06
duplicate of https://github.com/hiennguyen92/flutter_callkit_incoming/issues/12

**Closed** 2022-01-14 12:19 UTC
