### ISSUE TITLE
Semantic Issue (Xcode): Property 'timeSensitiveSetting' not found on object of type 'UNNotificationSettings *'

### ISSUE THREAD

**Issue by NathanaelNeria** [hiennguyen92/flutter_callkit_incoming#125] opened 2022-05-17 07:20 UTC
I use FirebaseMessaging.instance.getAPNSToken() to get APNS token using Firebase but keeps returning a null value. I've tried to:

delete the app
delete podfile.lock
flutter clean
flutter run
Reinstalling the app causes a semantic error error

<img width="657" alt="Screen Shot 2022-05-13 at 15 47 20" src="https://user-images.githubusercontent.com/16277640/168752672-3ac33cec-7ee9-4ad4-98ef-c7b3f8a6c8ab.png">

Please help, can't seem to find the proper solution for this issue. Thank you

**Comment by hiennguyen92** [comment] 2022-05-20 21:06
I cannot reproduce this issue. or this issue is out of scope of this package

**Closed** 2022-05-26 17:48 UTC
